export const MapConstants = {
    DEFAULT_SCALE: 90,
    MINI_MAP_SCALE: 20,
    GRID_SIZE: 15,
    LABEL_GUTTER: 30,
    // MIN_ZOOM_THRESHOLD: 50,
    INACTIVITY_TIMEOUT: 2000,
    // ZOOM_ANIMATION_DURATION: 400,
    PAN_SPEED: 15,
    CLICK_MAX_MS: 250,
    LONG_PRESS_MS: 600,
    DRAG_THRESHOLD_PX: 6,
    SONAR_PERSISTENCE_MS: 8000
};

export const MapStates = {
    PAN: 'PAN',
    ANIMATING: 'ANIMATING',
    SELECT_SQUARE: 'SELECT_SQUARE',
    SELECT_ROW: 'SELECT_ROW',
    SELECT_COLUMN: 'SELECT_COLUMN',
    SELECT_SECTOR: 'SELECT_SECTOR',
};

export const MapIntents = {
    NAVIGATE: 'NAVIGATE',
    TORPEDO: 'TORPEDO',
    MINE_LAY: 'MINE_LAY',
    MINE_SELECT_ACTIVE: 'MINE_SELECT_ACTIVE',
    POSITION_SELECT: 'POSITION_SELECT',
    ROW_SELECT: 'ROW_SELECT',
    COLUMN_SELECT: 'COLUMN_SELECT',
    SECTOR_SELECT: 'SECTOR_SELECT',
};

